import { db } from "./firebase";
import {
  collection,
  addDoc,
  doc,
  getDoc,
  serverTimestamp,
  query,
  where,
  orderBy,
  limit,
  getDocs,
  Timestamp,
} from "firebase/firestore";
import type { DatapackSpec } from "./datapackPrompt";

export type DatapackDoc = DatapackSpec & {
  uid: string | null;
  createdAt?: Timestamp;
};

export async function saveDatapack(datapack: DatapackSpec, uid?: string | null) {
  const docRef = await addDoc(collection(db, "datapacks"), {
    ...datapack,
    uid: uid ?? null,
    createdAt: serverTimestamp(),
  });

  return docRef.id;
}

export async function readDatapack(id: string) {
  const snap = await getDoc(doc(db, "datapacks", id));
  return snap.exists() ? (snap.data() as DatapackDoc) : null;
}

/**
 * Fetch the most recent datapacks generated by a specific user.
 * NOTE: Firestore may ask you to create an index the first time you run this (it will give you a link).
 */
export async function listDatapacksByUser(uid: string, max = 50) {
  const q = query(
    collection(db, "datapacks"),
    where("uid", "==", uid),
    orderBy("createdAt", "desc"),
    limit(max),
  );

  const snap = await getDocs(q);

  return snap.docs.map((d) => ({
    id: d.id,
    ...(d.data() as DatapackDoc),
  }));
}